### ISSUE TITLE
Thanks Stingrey

### ISSUE THREAD

**Issue by themaoci** [This-Enby-Leaks-Your-Paste/Maoci-Tarkov-Internal#1]
i know who leak that and how fucking old that source is ;)

i have one fully reworked ( also you didnt bought the cheat at all ) 

this is link to proof how old is this shit
https://github.com/themaoci/UnhandledExceptionsShower

**Comment by Team-G0df4th3r** [comment]
not me /closed

**Comment by themaoci** [comment]
yes you are. Noone else has that source. Only Stingrey aka Void on UC

<link> https://github.com/voidzero-development/TarkovInternals/tree/master/TheMaoci-Internal
this is from where you took it and only this place has it where last update was 3 months ago
